version: '2'

services:
  tiwengo:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      TIWENGO_BASE_URL: "http://localhost"
      TIWENGO_SHORT_URL: "https://shorturl.for.sms"
      TCCG_BASE_URL: "https://64c89918-4e80-4252-aef1-e52e6c774add.mock.pstmn.io"
      TOKEN_SECRET: "secret.token.for.login"
      DB_HOST: "mysql"
      DB_USERNAME: "tiwengo"
      DB_PASSWORD: "tiwengopassword"
      DB_NAME: "tiwengo"
      REDIS_HOST: "redis"
      SMS_UID: "smsuid"
      SMS_PWD: "smspassword"
      API_LIMIT_RATE: "10-S"
    ports:
      - 80:6080
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'tiwengo'
      MYSQL_USER: 'tiwengo'
      MYSQL_PASSWORD: 'tiwengopassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:6.0.9
    restart: always
    ports:
      - 6379:6379
volumes:
  db:
    driver: local
